{
    "openapi": "3.0.3",
    "info": {
        "title": "Todolist RESTful API",
        "version": "1",
        "description": "OpenAPI for Todolist RESTful API",
        "termsOfService": "https://www.arulproject.com",
        "contact": {
            "name": "Syahrul",
            "email": "arulproject@gmail.com",
            "url": "https://www.arulproject.com"
        },
        "license": {
            "name": "APACHE 2.0",
            "url": "https://apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers": [
        {
            "description": "Todolist RESTfull API Server",
            "url": "https://{environment}.arulproject.com/api/v1",
            "variables": {
                "environment": {
                    "default": "dev",
                    "description": "Server Environtment",
                    "enum": [
                        "dev",
                        "ga",
                        "prod"
                    ]
                }
            }
        }
    ],
    "externalDocs": {
        "description": "Youtube Programmer Zaman Now",
        "url": "https://www.youtube.com"
    },
    "paths": {
        "/todolist": {
            "get": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Get all todolist",
                "description": "Get all active todolist by default",
                "responses": {
                    "200": {
                        "description": "Success get all todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/arrayTodolist"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get all todolist",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": [
                                                    "Java",
                                                    "Programming"
                                                ]
                                            },
                                            {
                                                "id": "2",
                                                "name": "PHP",
                                                "priority": 2,
                                                "tags": [
                                                    "PHP",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "include done",
                        "in": "query",
                        "required": false,
                        "description": "Is include done todolist",
                        "schema": {
                            "type": "boolean",
                            "nullable": true,
                            "default": false
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter todolist by name",
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "Java": {
                                "value": "Java",
                                "description": "Example name Java"
                            },
                            "php": {
                                "description": "Example name PHP",
                                "value": "PHP"
                            }
                        }
                    }
                ]
            },
            "post": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Create new todolist",
                "description": "Create new todolist to database",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },
                                "php": {
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags": [
                                            "PHP",
                                            "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success create todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success create java todolist",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": [
                                                    "Java",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    },
                                    "php": {
                                        "description": "Success create php todolist",
                                        "value": [
                                            {
                                                "id": "2",
                                                "name": "PHP",
                                                "priority": 2,
                                                "tags": [
                                                    "PHP",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/todolist/{todolistId}": {
            "delete": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Delete existing todolist",
                "description": "Delete existing todolist in database",
                "responses": {
                    "200": {
                        "description": "Success delete todolists",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success deelete todolist",
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failed delete not found todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Failed deelete todolist",
                                        "value": {
                                            "success": false
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "$ref": "#/components/parameters/TodolistId"
                    }
                ]
            },
            "put": {
                "security": [
                    {
                        "TodolistAuth": []
                    }
                ],
                "tags": [
                    "Todolist"
                ],
                "summary": "Update existing todolist",
                "description": "Update existing todolist in databse",
                "responses": {
                    "200": {
                        "description": "Success Update todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success create java todolist",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": [
                                                    "Java",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    },
                                    "php": {
                                        "description": "Success create php todolist",
                                        "value": [
                                            {
                                                "id": "2",
                                                "name": "PHP",
                                                "priority": 2,
                                                "tags": [
                                                    "PHP",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "$ref": "#/components/parameters/TodolistId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },
                                "php": {
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags": [
                                            "PHP",
                                            "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "TodolistAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-KEY",
                "description": "Authentication for Todolist RESTful API"
            }
        },
        "parameters": {
            "TodolistId": {
                "name": "todolistId",
                "in": "path",
                "required": true,
                "description": "Todolist id for updated",
                "schema": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "java": {
                        "description": "Sample todolist id for Java",
                        "value": 1
                    },
                    "php": {
                        "description": "Sample todolist id for PHP",
                        "value": "2"
                    }
                }
            }
        },
        "schemas": {
            "Todolist": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "number",
                        "format": "int32"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "CreateOrUpdateTodolist": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "minLength": 1,
                        "required": [
                            "true"
                        ]
                    },
                    "priority": {
                        "type": "integer",
                        "format": "int32",
                        "default": 1,
                        "required": [
                            "true"
                        ]
                    },
                    "tags": {
                        "type": "array",
                        "required": [
                            "false"
                        ],
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "minLength": 1
                        }
                    }
                }
            },
            "arrayTodolist": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Todolist"
                }
            }
        }
    }
}